rtfd/sphinxcontrib-dotnetdomain

- sphinxcontrib/dotnetdomain.py
- tests/test_reference_definitions.py
- tests/test_signature.py
Breaks out parsing to DotNetObject class and child class regexes. Addresses some
of the issues with backtick notation and method signatures. Fixes #2, fixes #5.
> Separate parsing of callable/non-callable constraint signatures

- sphinxcontrib/dotnetdomain.py
- tests/test_reference_definitions.py
- tests/test_signature.py
Track unknown parsing as expected failures for now
Depends on #7
> Add failing tests for unknown parsing for now

- sphinxcontrib/dotnetdomain.py
- tests/test_reference_definitions.py
- tests/test_signature.py
This adds basic parsing for #ctor methods.
Depends on #7, fixes #4.
> Fix ctor parsing

- sphinxcontrib/dotnetdomain.py
- tests/test_reference_definitions.py
This adds multiple levels of nesting tracking for prefixes, fixes #3
> Add history of prefixes to nested object tracking

- tests/test_xref.py
- tests/util.py
This adds mocking on calls/returns to domain find_obj. This allows for testing
by writing inline references in test cases.
There are several failing test cases that were surfaced with testing. These
issues will be opened and resolved separately:
* Non-nestable objects are not propagating the dn:prefix set in temporary data
* Domain objects with colliding names but differing types are not separately
addressable
Fixes #6
> Add cross reference testing

- sphinxcontrib/dotnetdomain.py
- tests/test_xref.py
Makes the following changes:
* Drops unnecessary ported code
* Supports accidental titled references, ie: `FooBar<T>`. Normally, this is
processed as a Sphinx titled link. We will interpret references linking to T
as a mistake.
* Moves data from `temp_data` to `ref_context`, and makes use of AnyXRefRole to
automatically move env `ref_context` to refnodes
Depends on #13
> Xref cleanup

- sphinxcontrib/dotnetdomain.py
- tests/test_reference_definitions.py
- tests/test_signature.py
Addresses special operator syntax on UIDs, including:
* Prefix.operator ==(args)
* Prefix.operator !=(args)
* Prefix.operator true(args)
And so on, from overloadable operators at:
https://msdn.microsoft.com/en-us/library/8edha89s.aspx
* Prefix.implicit operator Prefix.ReturnType(arg)
As well as the invalid, but still parseable for our use case:
* Prefix.Foo(args)
This closes #12, which is an issue with argument ids, not fullName ids, which
we only have to use in argument lists currently.
> This adds the special syntax required for operators, with test cases

- sphinxcontrib/dotnetdomain.py
- tests/test_xref.py
- tests/util.py
This allows for addressing overloading names of differing types and proper
indexing to support all of this. This cleans up some of the indexing and updates
tests back to calling the long object type name, which is easier to use from
tests as a reference to the short reference type name.
This fixes #15 
This could also introduce problems with display which I am unable to test at the moment, will revisit this shortly
> Adds indexing to (object type, object name), instead of just object name

- sphinxcontrib/dotnetdomain.py
- tests/test_signature.py
This supports named types, such as `Foo<Bar>`.
> Update generic regex parsing to include named types

- sphinxcontrib/dotnetdomain.py
- tests/test_reference_definitions.py
- tests/test_xref.py
- tests/util.py
Both short and long directives will create an identical object. Xrefs can then
be either short or long -- they will both resolve to the same object, regardless
of whether the directive was short or long.
> Allow for both short and long directives and xrefs

- tests/test_reference_definitions.py
Mostly dropping named arguments for unnamed arguments
> Clean up argument tests

- docs/index.rst
- docs/syntax.rst
- sphinxcontrib/dotnetdomain.py
- tests/test_reference_definitions.py
Adds some options as discussed as part of #25. This adds public, protected, and
static modifiers to constructs, which will show in display.  Property and field
options currently do not yet affect display.
> Adds some option parsing to constructs and property/fields

- sphinxcontrib/dotnetdomain.py
- tests/test_signature.py
Adds support for syntax that doesn't match `Foo.Bar.#ctor`
> Fix parsing errors on ctor definitions

- sphinxcontrib/dotnetdomain.py
- tests/test_signature.py
Not sure exactly what this syntax is, it is common in reference links in api
output and related to #11.
> Add parsing for Foo{Bar{Baz}} style generics

- sphinxcontrib/dotnetdomain.py
- tests/test_reference_definitions.py
- tests/test_signature.py
This drops support for declarations like:
Foo.operator ==(T1, T2)
and instead expects:
Foo.op_Equal(T1, T2)
Fixes #31
> Drop code style operator syntax for op_Name syntax

- sphinxcontrib/dotnetdomain.py
```
Exception occurred:
File "/Users/anthony/.pyenv/versions/sphinx34/lib/python3.4/site-packages/sphinxcontrib/dotnetdomain.py", line 510, in generate
objects = sorted(self.domain.data['objects'].iteritems(),
AttributeError: 'dict' object has no attribute 'iteritems'
The full traceback has been saved in /var/folders/0z/3wz65d6s1dvcrqnhxqd1kvjr0000gn/T/sphinx-err-fvx0wshw.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```
> Incompatible py3 code

- prospector.yml
- sphinxcontrib/dotnetdomain.py
- tests/test_xref.py
- tests/util.py
This addresses a number of linking issues, and includes a light refactor of how
we are building up the domain data.
This drops the need for accumulating a special dictionary using the format:
```
(object type, object name) -> (object full name, object role type)
```
This was originally written this way to combine roles like `class` and `cls`
into a single lookup. Instead, this improves on the role mapping and doesn't
explicitly state the object type. The domain object mapping now uses the common
format of:
```
object_name -> (object full name, object role type)
```
The only deficiency of this is that when multiple objects have the same name,
but different types, the first object will be the one to receive reference
links. This shouldn't be an issue for most use cases however.
* Objects …
> Fix a number of linking issues

- sphinxcontrib/dotnetdomain.py
- tests/test_fields.py
This adds nested parameter linking to parameter and return types. This uses a
special output format from the autoapi output to link reference types.
Refs rtfd/sphinx-autoapi#66
> Add nested parameter linking

- .travis.yml
- sphinxcontrib/dotnetdomain.py
- tox.ini
Adds support for multiple formats of entry listing for the latex writer.  I'm
not sure if there is an easy way to mock out the latex builder, it seems to be
more complicated than the others. I added support for multiple sphinx version
tests anyways.
Fixes #56
> Add support for sphinx 1.4 latex writer

- sphinxcontrib/dotnetdomain.py
- tests/test_signature.py
- tox.ini
This assumes the contstruct name can be in one of the following formats:
```
foo[System.string] (indexer)
foo`1
foo{System.string}
```
> Adds support for .NET indexers

- sphinxcontrib/dotnetdomain.py
- tests/test_reference_definitions.py
Properties should not have callable arguments
Fixes #50
> Remove arguments from property display

- LICENSE
- MANIFEST.in
I'm packaging `sphinxcontrib-dotnetdomain` for [Conda-Forge](https://conda-forge.org/).  Based on your [`setup.py`](https://github.com/rtfd/sphinxcontrib-dotnetdomain/blob/master/setup.py#L16), I see that the license is MIT.  This PR adds the `LICENSE` to your package. 
xref conda-forge/staged-recipes#6116
> Include LICENSE
